### ISSUE TITLE
What classes need to change to adapt the login/register to small screens like iPhone?

### ISSUE THREAD

**Issue by udurraniAtPresage** [kennedymwavu/frbs-examples#1]
I am learning bootstrap and trying to modify the classes you used to make the login page responsive to small screens. With current classes in your example, the login/register form does not adapt to a small screen like iPhone. I was wondering which classes do I need to change? I tried `container-fluid` in `create_card` and `tabPanelBody` with 100% width of form elements. But nothing changes. Any ideas what I need to change?
![image](https://github.com/kennedymwavu/frbs-examples/assets/142413619/dd5c229d-d472-46cf-bc35-c3a4b3707e4e)

**Comment by kennedymwavu** [comment]
Hi @udurraniAtPresage,
Thanks for noticing that issue.
It was occurring because I had fixed width for the inputs (400px).
The solution is to set the max width of the form container to 100%.
I've fixed it [here](https://github.com/kennedymwavu/frbs-examples/blob/fbad458ee01e500ad3f434f8a039f521693edec5/shiny/R/mod_auth_ui.R#L12)

**Comment by udurraniAtPresage** [comment]
Thanks!
